### ISSUE TITLE
implementing in capacitor with angular

### ISSUE THREAD

**Issue by indrapalijama** [aparajita/capacitor-biometric-auth#10]
hi, is there a tutorial on how i can implemented this plugin in angular? from the demo version that you provided, it's using vue.

somehow i try to implemented it in my apps and build it to iOS, but it got this error : 
⚡️  WebView loaded
⚡️  [log] - begin init biometric..
⚡️  [error] - Error during biometric auth: {"code":"UNIMPLEMENTED"}

here's my code snippet : 
```
import { registerPlugin } from '@capacitor/core';
import { BiometricAuthPlugin } from '@aparajita/capacitor-biometric-auth';
const BiometricAuth = registerPlugin<BiometricAuthPlugin>('BiometricAuth');

  initBiometric() {
    console.log('begin init biometric..');
    BiometricAuth.checkBiometry()
      .then((result: any) => {
        console.log('auth biometry', result);
      })
      .catch((error: any) => {
        // Handle any errors
        console.error('Error during biometric check:', error);
      });
  }

  ngOnInit() {
    this.initBiometric();
  }
```

Thanks!

**Comment by aparajita** [comment]
Don't call `registerPlugin`.

```ts
import { BiometricAuth } from '@aparajita/capacitor-biometric-auth';
```

**Comment by indrapalijama** [comment]
whoa, now it works as it should. Thanks!
one thing, how can i check if the authenticated process is success? 
```
  initBiometric() {
    console.log('begin init biometric..');
    // const name = getBiometryName;
    console.log('biometric name', name);
    BiometricAuth.checkBiometry()
      .then((result: CheckBiometryResult) => {
        console.log('check biometry', result);
        if (result.isAvailable) {
          BiometricAuth.authenticate().then((res) => {
            console.log('success?', res);
          });
        }
      })
      .catch((error: any) => {
        // Handle any errors
        console.error('Error during biometric check:', error);
      });
  }
```

when i call authenticate(), my console that write success is undefined.
Thanks!

**Comment by aparajita** [comment]
You should expect no more or less than exactly what the docs say:

> If authentication succeeds, the Promise resolves. If authentication fails, the Promise is rejected with a BiometryError

**Comment by indrapalijama** [comment]
> You should expect no more or less than exactly what the docs say:
> 
> 
> 
> > If authentication succeeds, the Promise resolves. If authentication fails, the Promise is rejected with a BiometryError

my bad, got it! Thanks, really appreciate it
