### ISSUE TITLE
Crashes on iOS 16.4

### ISSUE THREAD

**Issue by oliveryasuna** [aparajita/capacitor-biometric-auth#14]
My code is pretty much the same as the demo code. Crashes on iOS 16.4 simulator.

**Comment by aparajita** [comment]
It's working perfectly here with both Face ID and Touch ID in the simulator, and I haven't had any other reports of crashes. Seeing your code would help.

**Comment by aparajita** [comment]
I see you closed it, does that mean you fixed the issue?

**Comment by oliveryasuna** [comment]
@aparajita Sorry, I totally forgot about this issue. Looks like I solved it and closed the issue while you were testing.
