### ISSUE TITLE
OAuth linking?

### ISSUE THREAD

**Issue by tommyc38** [aparajita/capacitor-biometric-auth#17]
Forgive me if this is a dumb question but how do I link biometric authentication with OAuth?  For example, I am using firebase and allow users to sign in via username/password, google, etc.  If a user has never logged in via username/password (which is the credential I would expect biometric auth to give me from the keychain?), how do I link their biometric auth data to their OAuth provider to show them as logged in?  Any info here would be appreciated!

**Comment by aparajita** [comment]
This plugin only presents the system biometry, which either succeeds or fails. It has no concept of username/password, or any other data, as that is separate from biometric authorization. Think of it this way: biometric auth is the key to the lock of a safe. The key only knows if it fits the lock or not. It has no idea what's in the safe.

To store secure data such as credentials, you'll want to use this plugin in conjunction with [capacitor-secure-storage](https://github.com/aparajita/capacitor-secure-storage). As for linking that data with OAuth, I haven't got clue.
