### ISSUE TITLE
iOS requires "NSFaceIDUsageDescription" now

### ISSUE THREAD

**Issue by danbaechtold** [aparajita/capacitor-biometric-auth#19]
For Face-ID to work on iOS, the "NSFaceIDUsageDescription" has to be set in Info.plist now.

Would be nice to have this mentioned in the docs, thank you.

**Comment by aparajita** [comment]
Thanks for pointing it out, that has actually been required for a few years. I thought I had mentioned that in the docs, I'll add it now.

**Comment by aparajita** [comment]
Gotta love github copilot — it literally wrote all of it for me!
