### ISSUE TITLE
Background Issue

### ISSUE THREAD

**Issue by schnouz** [aparajita/capacitor-biometric-auth#2]
Hi there,

I'm not sure if it's related to this plugin but I got this gray background each time the biometric is fired.

![issue](https://user-images.githubusercontent.com/13222971/189209606-25490ef4-98bc-43dd-a6e8-fef281f23802.png)

Have you already encounter this kind of issue ?
Regards

**Comment by aparajita** [comment]
That's odd, what iOS version? Simulator or real device?

**Comment by aparajita** [comment]
Note that biometrics actually suspends the app, so if your app is hiding the screen on suspend, that's what you are seeing.

**Comment by schnouz** [comment]
Thanks for the info, it leads me to the good path and this was caused from another plugin :)
