### ISSUE TITLE
error instanceof BiometryError, error.code typing

### ISSUE THREAD

**Issue by aeharding** [aparajita/capacitor-biometric-auth#20]
For developer experience with typescript, I want to do `error instanceof BiometryError` like the following:

```ts

    try {
      await BiometricAuth.authenticate({
        allowDeviceCredential: true,
      });
    } catch (error) {
      if (error instanceof BiometryError && error.code === 'biometryNotEnrolled') {
         // do thing with error.code
      }

      throw error;
    }
```

Because `error instanceof BiometryError` evaluates to false, I have to do the following:

```ts

    try {
      await BiometricAuth.authenticate({
        allowDeviceCredential: true,
      });
    } catch (error) {
      if (error && typeof error === 'object' &&'code' in error && error.code === 'biometryNotEnrolled') {
        
      }
      throw error;
    }
```

or I have to unsafely cast.

Also, `BiometryError.code` is typed as string, it would be nice if it was BiometryErrorType.

Thank you!

**Comment by aparajita** [comment]
The error thrown by any Capacitor plugin is actually an instance of `CapacitorException`. I'm not sure if that's something that happened after I originally wrote this plugin, because I don't remember that being the case.

Even if I intercept the exception and throw a `BiometryError` instance, you would still need a type guard because Typescript does not type `catch` variables. So you can achieve what you want now like this:

```ts
interface TypedBiometryError extends BiometryError {
  code: BiometryErrorType
}

async function showErrorAlert(error: TypedBiometryError): Promise<void> {
  await showAlert(`${error.message} [${error.code}].`);
}

function isBiometryError(error: unknown): error is TypedBiometryError {
  return error instanceof CapacitorException;
}

function isBiometryError(error: unknown): error is TypedBiometryError {
  return error instanceof CapacitorException;
}

async function authenticate(): Promise<void> {
    try {
      await BiometricAuth.authenticate({
        allowDeviceCredential: true,
      });
    } catch (error) {
      // The type guard will ensure you compare error.code against a valid BiometryErrorType value
      if (isBiometryError(error) && error.code === BiometryErrorType.biometryNotEnrolled) {
        showAlert(error)
      }
      throw error;
    }
}
```

**Comment by aparajita** [comment]
In any case I should add that type guard function to the plugin and type `code` as `BiometryErrorType`.

**Comment by aparajita** [comment]
Thanks for the request, v6.0.0 has just been released that throws an instance of `BiometryError` from `authenticate()`, and `BiometryError.code` is typed as `BiometryErrorType`.
