### ISSUE TITLE
Trouble running pnpm build -- Unexpected token ! in JSON at position 0

### ISSUE THREAD

**Issue by TheIronMarx** [aparajita/capacitor-biometric-auth#23]
Hello again! At your suggestion [here](https://github.com/aparajita/capacitor-biometric-auth/issues/21#issuecomment-1857088237), I'm taking a crack at making the modifications discussed in #21. I admit to not having much experience with `pnpm` or `npm`. After getting `pnpm` installed, cloning my unmodified fork, then running `pnpm install`, finally running `pnpm build`, I receive the following output, ending with what looks like a syntax exception thrown.
```

> @aparajita/capacitor-biometric-auth@6.0.0 prebuild /Users/me/Desktop/capacitor-biometric-auth
> pnpm lint


> @aparajita/capacitor-biometric-auth@6.0.0 lint /Users/me/Desktop/capacitor-biometric-auth
> pnpm lint.eslint . && pnpm lint.prettier '**/*.{js,mjs,ts,json,md,java}' && pnpm lint.tsc && swiftly ios


> @aparajita/capacitor-biometric-auth@6.0.0 lint.eslint /Users/me/Desktop/capacitor-biometric-auth
> eslint --fix --cache --ext .js,.cjs,.mjs,.ts --max-warnings 0 "."


> @aparajita/capacitor-biometric-auth@6.0.0 lint.prettier /Users/me/Desktop/capacitor-biometric-auth
> prettier --write --cache --list-different "**/*.{js,mjs,ts,json,md,java}"


> @aparajita/capacitor-biometric-auth@6.0.0 lint.tsc /Users/me/Desktop/capacitor-biometric-auth
> tsc --noEmit

Unexpected token ! in JSON at position 0
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

I wish I knew what JSON it was referring to. Does this seem like an issue on my side? If so, any suggestions to resolve it?

**Comment by TheIronMarx** [comment]
After digging into it, I was able to get further by omitting `&& swiftly ios` from `lint` in the scripts list in `package.json`. Trying to search for "swiftly ios" returns some ambiguous results. I'm not sure what it is or does.

**Comment by aparajita** [comment]
You can just do this to build the plugin:

```shell
node_modules/.bin/rollup -c rollup.config.mj
```

**Comment by aparajita** [comment]
To do the same for iOS, remove [these lines](https://github.com/aparajita/capacitor-biometric-auth/blob/84968821b838d61d248f89ab224a0f9e7b36164b/ios/Plugin/Plugin.swift#L100-L111).

**Comment by aparajita** [comment]
What package manager are you using, yarn?

**Comment by TheIronMarx** [comment]
Yes, yarn. I've had success modifying, building, and bringing in the project as a dependency. Again, only by removing the `swiftly ios`, which we still can't figure out what it is.

**Comment by aparajita** [comment]
`swifly ios` uses `swiftlint` to lint the ios code and depends on having the `swiftlint` binary installed.
