### ISSUE TITLE
React, Error: "systemCancel", when biometric authentication in the app start up

### ISSUE THREAD

**Issue by francisdurairaj** [aparajita/capacitor-biometric-auth#25]
React, Capacitor v5
Device: oneplus 11r, Android 14
Steps to reproduce:

call BiometricAuth.authenticate({ allowDeviceCredential: false }) in useeffect
Error appears

**Comment by aparajita** [comment]
I need more details.

- What kind of error?
- What is the error message?
- Can you inspect the app with Chrome and get a stack trace?

**Comment by aparajita** [comment]
Did you call `checkBiometry()` BEFORE calling `authenticate()`?

**Comment by francisdurairaj** [comment]
I use the given code in login tsx file. 

const checkAuthCallback = useCallback(async () => {
   try {
      const result = await BiometricAuth.checkBiometry();
      if(result.biometryType == BiometryType.fingerprintAuthentication) {

         await BiometricAuth.authenticate({
            reason: 'Authenticate',
            cancelTitle: 'Cancel',
            iosFallbackTitle: 'Touch ID for Login',
            androidTitle: 'Touch ID for Login',
            allowDeviceCredential: true,
            androidConfirmationRequired: false,
            andriodBiometryStrength: AndriodBiometryStrength,weak
         });
         handleRirect();
      }
   }
   catch(error){
      toast.error((error instanceof BiometryError) ? `(${error.code}): ${error.message}` : String(error));
   }
},[handleRirect]);

useEffect(() => {
   const doAuth = async () => {
      await checkAuthCallback();
   }
   doAuth();
}, [checkAuthCallback]);

**Comment by aparajita** [comment]
As the docs point out, `result.biometryType == BiometryType.fingerprintAuthentication` does not mean biometry is actually available. You need to check `result.isAvailable`.

- What is the value of `result.isAvailable`?
- Does the fingerprint authentication dialog come up at all?

I haven't tested on Android 14 yet, I will try tomorrow.

**Comment by francisdurairaj** [comment]
Yes we are getting the authentication. But after successful authentication getting systemcancel error. And again I have to click on button to check biometric. It works on the second time

First time I am getting error when triggered via button click it works.

**Comment by aparajita** [comment]
v7.1.1 has just been released with the Android bug fix.

**Comment by francisdurairaj** [comment]
I think it's rendering multiple times.. which causes the lib to throw 'systemcancel'.

**Comment by aparajita** [comment]
> I think it's rendering multiple times.. which causes the lib to throw 'systemcancel'.

I don't think that behavior is coming from my code.
