### ISSUE TITLE
White screen in my app during live reload mode after importing NSFaceIDUsageDescription in Info.plist

### ISSUE THREAD

**Issue by blinkdagger182** [aparajita/capacitor-biometric-auth#26]
Importing this in my Info.plist is causing a white screen when i try to run my app in live reload mode using
`ionic cap run ios -l --external`

```
 <key>NSFaceIDUsageDescription</key>
 <string>Allow the 'App' to use FaceID?</string>
```

Its deploying my app to a about:blank, and there is nothing informational both from the debugger and device logs
Any ideas how to resolve?

**Comment by aparajita** [comment]
Try the demo app with live reload. If that works, then figure out what is different in your project.
