### ISSUE TITLE
iOS Touch ID dialog displays when calling checkBiometry()

### ISSUE THREAD

**Issue by jcrawl3y** [aparajita/capacitor-biometric-auth#27]
iOS Touch ID dialog displays when checkBiometry() is called.
This doesn't seem like the expected behaviour - was just expecting the metadata to return.
I thought we called authenticate() to actually perform a touch ID or face ID on the device?

**Comment by aparajita** [comment]
Nope, checkBiometry() does not do that. There must be something in your code that is doing that.

**Comment by jcrawl3y** [comment]
Sorry, looks to be another lib in our app.  Thanks for confirming.  Closed this off.
