### ISSUE TITLE
feat: Capacitor 6 Support

### ISSUE THREAD

**Issue by ckoon-infopro** [aparajita/capacitor-biometric-auth#29]
Capacitor 6.0 has been announced, bringing support for Android 14 and iOS 17.
[https://ionic.io/blog/announcing-capacitor-6-0](https://ionic.io/blog/announcing-capacitor-6-0)

Updating Plugins to 6.0:
[https://capacitorjs.com/docs/updating/plugins/6-0](https://capacitorjs.com/docs/updating/plugins/6-0)

**Comment by aparajita** [comment]
Thanks for the heads up, will check it out.

**Comment by rricamar** [comment]
> Thanks for the heads up, will check it out.

Guess that you'll need to update as well the https://github.com/aparajita/capacitor-secure-storage plugin or any related Capacitor plugin... 😅 

Thanks! 🙏

**Comment by aparajita** [comment]
> Guess that you'll need to update as well the https://github.com/aparajita/capacitor-secure-storage plugin or any related Capacitor plugin... 😅

Of course, all of my plugins will need to be updated.

**Comment by aparajita** [comment]
capacitor-biometric-auth and capacitor-secure-storage have been updated.
