### ISSUE TITLE
Question: Customize Biometric Input Prompt Screen

### ISSUE THREAD

**Issue by clowcher** [aparajita/capacitor-biometric-auth#30]
Hello, thank you for making this plugin! 

I have pretty much everything set up and working but was wondering if it's possible to customize the screen where you input your passcode? 

This is a fallback scenario on iOS where a user opts into using biometrics but has disabled Face ID/Fingerprints. 

`iosFallbackTitle: 'Use passcode',`

![image](https://github.com/aparajita/capacitor-biometric-auth/assets/101572065/cb7aa292-da4b-4e21-ab1a-2d40f5cf4526)

Any help would be appreciated, even if we need to write some code outside of ionic, we're not totally sure where this comes from or if we can customize the page? It would be nice to be able to change the background color, add a logo and default to the numeric keyboard, etc, etc.

Thanks!

**Comment by aparajita** [comment]
That is a system prompt. For security reasons there is no way to prompt for the passcode outside of the system-provided prompts.
