### ISSUE TITLE
Suggestion:  Device credentials

### ISSUE THREAD

**Issue by daniel-lujan** [aparajita/capacitor-biometric-auth#31]
Hello!

I would like some sort of Device Credential as result of user authentication. I wasn't able to find any documentation about device credentials so I am using this plugin does not have this feature.

The purpose of this would be crypting sensitive data, using some part of the Credential (maybe a hash string) to encrypt data and avoiding posible unauthorized access to information, forcing user to actually authenticate through my application to decrypt and read data.

I know I could use some user classical authentication approach, but I am precisely using biometric authentication as a more straightforward and simple way to authenticate who is accessing the data.

I am also aware that Android (and most likely, iOS), provide this kind of credentials, so I think it's quite possible.

**Comment by aparajita** [comment]
> The purpose of this would be crypting sensitive data, using some part of the Credential (maybe a hash string) to encrypt data and avoiding posible unauthorized access to information, forcing user to actually authenticate through my application to decrypt and read data.

Use this plugin in conjunction with my [secure-storage plugin](https://github.com/aparajita/capacitor-secure-storage). That's how I deal with user credentials. They are stored securely with secure-storage and the user has to authenticate with this plugin to access the credentials.

**Comment by nickhow83** [comment]
@aparajita is the combination of the two plugins really as simple as:

```
try {
  await BiometricAuth.authenticate();
  
  const value = await SecureStorage.get(
    'some_key',
    false,
    false
  );
} catcn (err) {
  // handle the error
}
```

**Comment by aparajita** [comment]
Yes, it's that simple.

**Comment by ms-emp** [comment]
@aparajita

I'm using it together with the [secure-storage plugin](https://github.com/aparajita/capacitor-secure-storage) to store if biometric login is enabled. Still, it does not get removed once the secure lock screen is disabled or changed (it looks like `setUserAuthenticationRequired` is not being set, see [here](https://github.com/aparajita/capacitor-secure-storage/blob/f0f6c7c1d2e9e30350ab20dd7327d69ad6e59b60/android/src/main/java/com/aparajita/capacitor/securestorage/SecureStorage.java)) is there a way to accomplish that when the user changes fingerprint the previously stored value that biometric is enabled should be invalidated?

**Comment by aparajita** [comment]
The native mobile SDKs do not provide a way to monitor changes to the user's biometric credentials. That would be a huge security hole.

It's up to you to remove credentials if the user has completely disabled biometric auth. The secure store plugin is concerned only with storing and retrieving data. The circumstances under which that happens is up to you.

**Comment by ms-emp** [comment]
@aparajita 

Right, but when you use `setUserAuthenticationRequired` on Android KeyStore, anything stored will get invalidated when the user changes the biometric on the device. see [here](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder#setUserAuthenticationRequired(boolean)). 

See similar issue [here](https://github.com/martinkasa/capacitor-secure-storage-plugin/issues/16)

**Comment by aparajita** [comment]
Yes, I see it is possible, but I just don't have any time to implement that right now. PRs welcome.
