### ISSUE TITLE
Auth Validation

### ISSUE THREAD

**Issue by tommybananas** [aparajita/capacitor-biometric-auth#34]
Hey there, maybe I don't fully understand the flow here but I would imagine the authentication provider returning some kind of public key or piece of verifiable information such that your API would then feel confident generating an auth token upon the next authentication. Is that piece outside the scope of this or am I thinking about the intended implementation wrong?

**Comment by aparajita** [comment]
The basic workflow I and many others use is this:

1. You verify the user with their credentials (e.g. user/pass).
2. You check to see if biometric auth is available using the plugin.
3. If it's available, ask them if they want to use biometric auth.
4. If so, you use the plugin to actually do the biometric auth.
5. If that passes, you store the credentials securely, for example using my secure-storage plugin.
6. The next time you need to authorize the user, you present biometric auth.
7. If that passes, you retrieve the credentials from secure storage and log them in.
