### ISSUE TITLE
A way to determine pause duration in `addResumeListener`

### ISSUE THREAD

**Issue by fanckush** [aparajita/capacitor-biometric-auth#36]
Hello

Is there a way or a workaround to detect for how long the app was paused?
many banking apps for example don't require faceID when resumed immediately. but if you were gone for some specific time (for example longer than a minute) then you will prompted to authenticate again.

Is such behavior possible?

**Comment by aparajita** [comment]
- Use the Capacitor App plugin to add a listener for pause and resume.
- In the pause callback, save the current time using the Preferences plugin
- On resume, read the pref and compare to the current time.

**Comment by fanckush** [comment]
thank you!
