### ISSUE TITLE
Detect if the user changed biometric/fingerprint

### ISSUE THREAD

**Issue by ms-emp** [aparajita/capacitor-biometric-auth#40]
Using this plugin, how can I check if the user changed his enrolled fingerprint/face after they enabled biometric login?

On Android, it looks like we should be able to accomplish using [setUserAuthenticationRequired](https://developer.android.com/reference/android/security/keystore/KeyGenParameterSpec.Builder.html#setUserAuthenticationRequired(boolean)), but I'm not familiar on how to use it.

**Comment by aparajita** [comment]
The native biometry APIs do not provide a way to tell if the biometry has changed. The Android reference you linked to relates to secure storage, which this plugin does not deal with at all.

See [here](https://github.com/aparajita/capacitor-biometric-auth/issues/31#issuecomment-2353704288) for a related discussion.
