### ISSUE TITLE
Android - Detect available type

### ISSUE THREAD

**Issue by ms-emp** [aparajita/capacitor-biometric-auth#41]
Hi,

Consider the following scenario: an Android device that supports both fingerprint and face (and the device considers face as strong), but the user has only enrolled in face. In this case, `strongBiometryIsAvailable` will return true (because the user is enrolled in face), while the `availableType` will indicate fingerprint (as it is generally regarded as more secure). However, the actual available type is face?!

**Comment by aparajita** [comment]
Ah, that would explain it. I wouldn't count on an emulator to correctly handle all biometry.

**Comment by ms-emp** [comment]
So, is there any case we should have Face Authentication available on Android as a strong biometric?

**Comment by aparajita** [comment]
Ask perplexity.ai or ChatGPT if there are any Android phones whose face unlock qualifies as strong biometry. 

Again, don't count on the emulator for those phones working exactly like the physical device.
