### ISSUE TITLE
implement biometric on app resume

### ISSUE THREAD

**Issue by moh4sa** [aparajita/capacitor-biometric-auth#42]
This is a question, not an issue. I'm trying to use this plugin to prompt users for authentication when the app is in the background. However, when the biometric prompt is displayed, the operating system pauses the app. After successful authentication, the app resumes, which causes this feature to enter an infinite loop.

I am using Platform from @ionic/angular/standalone to track the app resume and pause event. 

Do you have a better idea of how to implement this correctly? or fix this issue.

thank you!

**Comment by aparajita** [comment]
Set a global flag before presenting auth and clear it when it's done. On resume, if the flag is set, do not present auth.
