### ISSUE TITLE
Capacitor 5

### ISSUE THREAD

**Issue by NePheus** [aparajita/capacitor-biometric-auth#6]
Are you going to update the plugin to support Capacitor 5? Capacitor 5 should be released soon.

https://capacitorjs.com/docs/next/updating/plugins/5-0

**Comment by aparajita** [comment]
Yes, when it reaches RC.

**Comment by AE1NS** [comment]
https://ionic.io/blog/announcing-capacitor-5

PR created

**Comment by aparajita** [comment]
This week or next.

**Comment by aparajita** [comment]
Just released.
